# Generated by Django 5.0.3 on 2024-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_id_alter_invoice_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(related_name='addresses', through='core.UserAddress', to='core.user'),
        ),
    ]
